const initialMovies = {
  docs: [
    {
      id: 7322349,
      name: "97-я церемония вручения премии «Оскар»",
      alternativeName: "The Oscars",
      enName: null,
      type: "movie",
      typeNumber: 1,
      year: 2025,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 6.6,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 78,
        imdb: 644,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 182,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      poster: {
        url: "https://image.openmoviedb.com/kinopoisk-images/10703959/7d586741-75aa-4315-bdf0-79d3214655ad/orig",
        previewUrl:
          "https://image.openmoviedb.com/kinopoisk-images/10703959/7d586741-75aa-4315-bdf0-79d3214655ad/x1000",
      },
      genres: [
        {
          name: "церемония",
        },
      ],
      countries: [
        {
          name: "США",
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 6583705,
      name: null,
      alternativeName: "Pink Velvet 3: A Lesbian Odyssey",
      enName: null,
      type: "movie",
      typeNumber: 1,
      year: 2005,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 8.5,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 122,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 187,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: 18,
      genres: [
        {
          name: "для взрослых",
        },
      ],
      countries: [
        {
          name: "Великобритания",
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 7245042,
      name: "TheatreHD: Курентзис: Пассажирка",
      alternativeName: "Die Passagierin",
      enName: null,
      type: "movie",
      typeNumber: 1,
      year: 2010,
      description:
        "Первая сценическая постановке оперы Вайнберга о фашистском концлагере.",
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 171,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: 18,
      poster: {
        url: "https://image.openmoviedb.com/kinopoisk-images/4716873/795b8524-c1e6-46dd-9d11-4e823c91ce07/orig",
        previewUrl:
          "https://image.openmoviedb.com/kinopoisk-images/4716873/795b8524-c1e6-46dd-9d11-4e823c91ce07/x1000",
      },
      backdrop: {
        url: "https://image.openmoviedb.com/kinopoisk-ott-images/12808873/2a000001955b329ab35ff71d3031df076591/orig",
        previewUrl:
          "https://image.openmoviedb.com/kinopoisk-ott-images/12808873/2a000001955b329ab35ff71d3031df076591/x1000",
      },
      genres: [
        {
          name: "музыка",
        },
      ],
      countries: [
        {
          name: "Австрия",
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 7344744,
      name: null,
      alternativeName: "Zakham",
      type: "tv-series",
      typeNumber: 2,
      year: 2022,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 7.7,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 24,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: "драма",
        },
      ],
      countries: [
        {
          name: "Пакистан",
        },
      ],
      releaseYears: [
        {
          start: 2022,
          end: null,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 7343988,
      name: "Загадай свою смерть",
      alternativeName: "Girigo",
      type: "tv-series",
      typeNumber: 2,
      year: null,
      description:
        "Группа студентов пытается спастись от проклятого приложения.",
      shortDescription: null,
      status: "filming",
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: "ужасы",
        },
      ],
      countries: [
        {
          name: "Корея Южная",
        },
      ],
      releaseYears: [
        {
          start: null,
          end: null,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 7344538,
      name: null,
      alternativeName: "Inside Joke with Asif Ali",
      type: "tv-series",
      typeNumber: 2,
      year: 2018,
      description: null,
      shortDescription: null,
      status: "completed",
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: 35,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: "документальный",
        },
        {
          name: "ток-шоу",
        },
        {
          name: "комедия",
        },
      ],
      countries: [
        {
          name: "США",
        },
      ],
      releaseYears: [
        {
          start: 2018,
          end: 2018,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 7344556,
      name: null,
      alternativeName: "Uproarious",
      type: "tv-series",
      typeNumber: 2,
      year: 2016,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: 30,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: "комедия",
        },
      ],
      countries: [
        {
          name: "США",
        },
      ],
      releaseYears: [
        {
          start: 2016,
          end: null,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 7344377,
      name: null,
      alternativeName: "Problematic with Moshe Kasher",
      type: "tv-series",
      typeNumber: 2,
      year: 2017,
      description: null,
      shortDescription: null,
      status: "completed",
      rating: {
        kp: 0,
        imdb: 3.5,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 258,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: "комедия",
        },
      ],
      countries: [
        {
          name: "США",
        },
      ],
      releaseYears: [
        {
          start: 2017,
          end: 2017,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 7344367,
      name: null,
      alternativeName: "Tubbin' with Tash",
      type: "tv-series",
      typeNumber: 2,
      year: 2013,
      description: null,
      shortDescription: null,
      status: "completed",
      rating: {
        kp: 0,
        imdb: 6.1,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 41,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: "комедия",
        },
      ],
      countries: [
        {
          name: "США",
        },
      ],
      releaseYears: [
        {
          start: 2013,
          end: 2013,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 7346559,
      name: null,
      alternativeName: "Dinosaur Apocalypse",
      type: "tv-series",
      typeNumber: 2,
      year: 2022,
      description: null,
      shortDescription: null,
      status: "completed",
      rating: {
        kp: 0,
        imdb: 7.7,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 73,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: 51,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: "документальный",
        },
      ],
      countries: [
        {
          name: "Великобритания",
        },
      ],
      releaseYears: [
        {
          start: 2022,
          end: 2022,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
  ],
  total: 1077136,
  limit: 10,
  page: 1,
  pages: 107714,
};
module.exports = { initialMovies };